### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by jiashizuo** [ATP-BME/LGMF-GNN#1]
Thank you very much for the code! But I didn't find your paper, can you provide the paper, thanks!

**Comment by xdjwolf** [comment]
Thank you very much for the code! But I didn't find your paper, can you provide the paper, thanks!

**Comment by ATP-BME** [comment]
Thank you for your interest in our work! I’m glad you found the code useful. Our paper has just been published in Patterns. You can find it under the title “An objective quantitative diagnosis of depression using a local-to-global multimodal fusion graph neural network” by Liu, S. et al.  DOI: https://doi.org/10.1016/j.patter.2024.101081
